### ISSUE TITLE
Video is shifted in fullscreen mode

### ISSUE THREAD

**Issue by WesselKroos** [WesselKroos/chrome-youtube-ambilight#15]
It shifts the entire video in fullscreen or in big player mode (strangely it doesn't shift it in normal mode, but ambilight itself is still shifted). That's why I still cannot use it.
[Enabled](https://i.imgur.com/Qo3nz4D.jpg)
[Disabled](https://i.imgur.com/U1sxQ0U.jpg)

Extension installed from the Opera webstore, Monitor is still 21:9 aspect ratio.

_Originally posted by @iGerman00 in https://github.com/WesselKroos/chrome-youtube-ambilight/issues/14#issuecomment-572607545_

**Comment by WesselKroos** [comment]
@iGerman00 I can't seems to reproduce the video shifting with the version in the Opera webstore. I've set my monitor to the same resolution 2560x1080 but the video is centered for me: https://imgur.com/a/Uw3SK3g

I've tried some random ambilight settings as well but it's always centered so far. Are you sure it's not another extension in combination with the ambilight extension? Is it still not centered when you disable all other extensions and refresh the webpage?

**Comment by iGerman00** [comment]
> @iGerman00 I can't seems to reproduce the video shifting with the version in the Opera GX webstore. I've set my monitor to the same resolution 2560x1080 but the video is centered for me: https://imgur.com/a/Uw3SK3g
> 
> I've tried some random ambilight settings as well but it's always centered so far. Are you sure it's not another extension in combination with the ambilight extension? Is it still not centered when you disable all other extensions and refresh the webpage?

Actually I completely forgot other extensions exist. It works just fine when it's on its own. 

[Ultrawidify's ](https://github.com/xternal7/ultrawidify) the cause. It seems disabling that extension fixes the problem completely. I guess I should also report this to their github too.

**Comment by WesselKroos** [comment]
Resolved by af0a1b2b2bb97d2bc3a1cc9ea9c634505dd840e7

**Comment by WesselKroos** [comment]
@iGerman00 I've published version 2.30.2 in the Opera add-ons store which contains the fix. Can you verify that it's fixed?

**Comment by WesselKroos** [comment]
I assume it has been resolved.

**Comment by iGerman00** [comment]
> I assume it has been resolved.

Sorry, I can not verify at the moment since I’m way away from a pc, I’ll edit this whenever I try it out, thanks for the fix
